kind = "web"
previewPath = "/"
title = "Schatanonim Bot"
version = "1.0.0"
id = "artifacts/schatanonim-bot"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23750

[services.development]
run = "pnpm --filter @workspace/schatanonim-bot run dev"

[services.production]

[services.production.run]
args = ["python", "bot/main.py"]

[services.production.health.startup]
path = "/"

[services.env]
PORT = "23750"
BASE_PATH = "/"
